/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaJogo.java
 *
 * Created on May 25, 2010, 12:54:21 PM
 */

package gui;

import adedanha.Resultado;
import adedanha.Rodada;
import adedanha.Tema;
import controller.Controller;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.Map.Entry;
import java.util.TreeMap;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 * 
 * @author luizfelipe
 */
public class TelaJogo extends javax.swing.JFrame {
	/**
	 * Controlador do jogo.
	 */
	private Controller controller;

	/**
	 * Lista de usuarios para serem exibidos no chat.
	 */
	private Vector<String> usuarios;

	/**
	 * Rodada atual do jogo.
	 */
	private Rodada rodada_atual;

	/**
	 * Lista dos paineis dos temas
	 */
	private TreeMap<Tema, PanelTema> lst_panel_temas;

	/**
	 * Resultados para cada tema.
	 */
	private TreeMap<Tema, Resultado> resultados;

	/** Creates new form TelaJogo */
	public TelaJogo(Controller c) {
		controller = c;

		initComponents();

		usuarios = new Vector<String>(controller.get_user_list());
		lst_chat.setListData(usuarios);

		set_rodada_atual();

		Vector<Tema> temas = rodada_atual.get_temas();

		resultados = new TreeMap<Tema, Resultado>();

		for (Tema t : temas) {
			resultados.put(t, new Resultado());
		}

		initComponentsTema();
	}

	private void set_rodada_atual() {
		rodada_atual = controller.get_rodada_atual();

		set_num_rodada_atual();

		l_letra.setText(rodada_atual.get_letra().toString());
	}

	private void set_num_rodada_atual() {
		Integer i = controller.get_num_rodada_atual();

		l_rodada.setText(i.toString());
	}

	public TreeMap<Tema, Resultado> get_respostas() {
		for(Tema t: lst_panel_temas.keySet()){
			PanelTema pTema = lst_panel_temas.get(t);
			Resultado res = resultados.get(t);
			if(res != null){
				res.set_resposta(pTema.getResposta());
			}
		}
		return resultados;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		fr_chat = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		lst_chat = new javax.swing.JList();
		jScrollPane3 = new javax.swing.JScrollPane();
		ta_chat = new javax.swing.JTextArea();
		tf_chat = new javax.swing.JTextField();
		b_chat = new javax.swing.JButton();
		fr_rodada = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		l_letra = new javax.swing.JLabel();
		l_rodada = new javax.swing.JLabel();
		fr_jogo = new javax.swing.JPanel();
		jToggleButton2 = new javax.swing.JToggleButton();
		jToggleButton1 = new javax.swing.JToggleButton();

		setTitle("Tela Jogo");
		setResizable(false);

		addWindowListener(new WindowListener() {

			public void windowActivated(WindowEvent e) {
				// TODO Auto-generated method stub

			}

			public void windowClosed(WindowEvent e) {

			}

			public void windowClosing(WindowEvent e) {
				jToggleButton1ActionPerformed();

			}

			public void windowDeactivated(WindowEvent e) {

			}

			public void windowDeiconified(WindowEvent e) {
				// TODO Auto-generated method stub

			}

			public void windowIconified(WindowEvent e) {
				// TODO Auto-generated method stub

			}

			public void windowOpened(WindowEvent e) {
				// TODO Auto-generated method stub

			}

		});

		fr_chat.setBorder(javax.swing.BorderFactory.createTitledBorder(
				javax.swing.BorderFactory.createEtchedBorder(), " Chat "));

		lst_chat.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Lucas", "Luiz Felipe", "Thyago" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(lst_chat);

		ta_chat.setColumns(20);
		ta_chat.setEditable(false);
		ta_chat.setRows(5);
		jScrollPane3.setViewportView(ta_chat);

		tf_chat.setText("Mensagem...");
		tf_chat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tf_chatActionPerformed(evt);
			}
		});

		b_chat.setText("Enviar");

		b_chat.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				b_chatActionPerformed(e);

			}

		});

		javax.swing.GroupLayout fr_chatLayout = new javax.swing.GroupLayout(
				fr_chat);
		fr_chat.setLayout(fr_chatLayout);
		fr_chatLayout
				.setHorizontalGroup(fr_chatLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								fr_chatLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												fr_chatLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																tf_chat,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																512,
																Short.MAX_VALUE)
														.addComponent(
																jScrollPane3,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																512,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												fr_chatLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																b_chat,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																107,
																Short.MAX_VALUE))
										.addContainerGap()));
		fr_chatLayout
				.setVerticalGroup(fr_chatLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								fr_chatLayout
										.createSequentialGroup()
										.addGroup(
												fr_chatLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(
																jScrollPane3,
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																108,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												fr_chatLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																tf_chat,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(b_chat))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		fr_rodada.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Rodada "));
		fr_rodada.setPreferredSize(new java.awt.Dimension(652, 229));

		jLabel1.setText("Letra:");

		jLabel2.setText("Rodada:");

		l_letra.setFont(new java.awt.Font("Tahoma", 1, 15));

		l_rodada.setFont(new java.awt.Font("Tahoma", 1, 15));

		fr_jogo.setBorder(null);

		javax.swing.GroupLayout fr_jogoLayout = new javax.swing.GroupLayout(
				fr_jogo);
		fr_jogo.setLayout(fr_jogoLayout);
		fr_jogoLayout.setHorizontalGroup(fr_jogoLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 649,
				Short.MAX_VALUE));
		fr_jogoLayout.setVerticalGroup(fr_jogoLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 176,
				Short.MAX_VALUE));

		javax.swing.GroupLayout fr_rodadaLayout = new javax.swing.GroupLayout(
				fr_rodada);
		fr_rodada.setLayout(fr_rodadaLayout);
		fr_rodadaLayout
				.setHorizontalGroup(fr_rodadaLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								fr_rodadaLayout
										.createSequentialGroup()
										.addGap(10, 10, 10)
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												l_letra,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												25,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												l_rodada,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												25,
												javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(fr_jogo,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE));
		fr_rodadaLayout
				.setVerticalGroup(fr_rodadaLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								fr_rodadaLayout
										.createSequentialGroup()
										.addGroup(
												fr_rodadaLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(l_letra)
														.addComponent(jLabel2)
														.addComponent(l_rodada))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												fr_jogo,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jToggleButton2.setText("PARAR!");
		jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jToggleButton2ActionPerformed(evt);
			}
		});

		jToggleButton1.setText("Sair");
		jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jToggleButton1ActionPerformed();
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																fr_chat,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jToggleButton1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				565,
																				Short.MAX_VALUE)
																		.addComponent(
																				jToggleButton2))
														.addComponent(
																fr_rodada,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																661,
																Short.MAX_VALUE))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												fr_rodada,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												226, Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jToggleButton2)
														.addComponent(
																jToggleButton1))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												fr_chat,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit()
				.getScreenSize();
		setBounds((screenSize.width - 685) / 2, (screenSize.height - 500) / 2,
				685, 500);
	}// </editor-fold>//GEN-END:initComponents

	private void tf_chatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tf_chatActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_tf_chatActionPerformed

	private void b_chatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_b_chatActionPerformed
		String newText = "\n"
				+ controller.getCliente().getUser().get_username() + " : "
				+ tf_chat.getText();

		tf_chat.setText("");
		controller.enviaMensagem(newText);
	}// GEN-LAST:event_b_chatActionPerformed

	private void jToggleButton1ActionPerformed() {// GEN-FIRST:event_jToggleButton1ActionPerformed
		controller.remove_usuario();
		controller.setTelaJogo(null);
		this.setVisible(false);
		new TelaInicial().setVisible(true);
	}

	private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton2ActionPerformed
		Runnable run = new Runnable() {

			public void run() {
				for (Entry<Tema, PanelTema> i : lst_panel_temas.entrySet()) {
					if (i.getValue().getResposta().isEmpty()) {
						JOptionPane.showMessageDialog(null,
								"Voce deve preencher todas as respostas. O tema "
										+ i.getKey().get_nome()
										+ " esta vazio.", "Jogo",
								JOptionPane.ERROR_MESSAGE);
						return;
					} else if (i.getValue().getResposta().toUpperCase()
							.startsWith(rodada_atual.get_letra().toString()) == false) {
						JOptionPane.showMessageDialog(null, "O tema "
								+ i.getKey().get_nome()
								+ " nao comeca com a letra da rodada.", "Jogo",
								JOptionPane.ERROR_MESSAGE);
						return;
					}
				}

				for (Entry<Tema, Resultado> e : resultados.entrySet()) {
					Resultado r = e.getValue();

					r.set_resposta(lst_panel_temas.get(e.getKey())
							.getResposta());
				}

				controller.pede_stop();
			}
		};
		SwingUtilities.invokeLater(run);
	}// GEN-LAST:event_jToggleButton2ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton b_chat;
	private javax.swing.JPanel fr_chat;
	private javax.swing.JPanel fr_jogo;
	private javax.swing.JPanel fr_rodada;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JToggleButton jToggleButton1;
	private javax.swing.JToggleButton jToggleButton2;
	private javax.swing.JLabel l_letra;
	private javax.swing.JLabel l_rodada;
	private javax.swing.JList lst_chat;
	private javax.swing.JTextArea ta_chat;
	private javax.swing.JTextField tf_chat;

	// End of variables declaration//GEN-END:variables

	private void initComponentsTema() {
		fr_jogo.setLayout(new GridLayout(4, 3));
		lst_panel_temas = new TreeMap<Tema, PanelTema>();
		PanelTema panelTema;
		Vector<Tema> temas = rodada_atual.get_temas();
		for (Tema t : temas) {
			panelTema = new PanelTema(t.get_nome());
			lst_panel_temas.put(t, panelTema);
			fr_jogo.add(panelTema);
		}
	}

	public void setMensagem(String texto) {
		if (ta_chat.getText() != null && ta_chat.getText().length() > 0) {
			ta_chat.append(texto);
		} else {
			ta_chat.setText(texto);
		}
	}

	public void atualizaListaJogadores() {
		usuarios = new Vector<String>(controller.get_user_list());
		if (lst_chat.getGraphics() != null) {
			lst_chat.setListData(usuarios);
			lst_chat.update(lst_chat.getGraphics());
		}
	}

	public void terminaJogo() {
		this.setVisible(false);
		new TelaInicial().setVisible(true);
	}

	public void stop() {
		Runnable run = new Runnable() {

			public void run() {
				for (Tema t : lst_panel_temas.keySet()) {

					PanelTema panelTema = lst_panel_temas.get(t);
					panelTema.bloquear();

				}
				jToggleButton2.setEnabled(false);
				
			}
		};
		SwingUtilities.invokeLater(run);

	}

}
