/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelTema.java
 *
 * Created on Jun 23, 2010, 8:21:21 AM
 */

package gui;

/**
 *
 * @author luizfelipe
 */
public class PanelTema extends javax.swing.JPanel {

    /** Creates new form PanelTema */
    public PanelTema(String tema) {
        initComponents();
        tf_tema.setText("");
        l_tema.setText(tema + ":");
    }

    public String getResposta() {
    	return tf_tema.getText();
    }

    public void setResposta(String s) {
        tf_tema.setText(s);
    }

    public String getTema() {
        return l_tema.getText();
    }

    public void setTema(String s) {
        l_tema.setText(s);
    }
    
    public void bloquear(){
    	tf_tema.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_tema = new javax.swing.JTextField();
        l_tema = new javax.swing.JLabel();

        tf_tema.setText("jTextField1");

        l_tema.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_tema, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_tema, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(l_tema)
                .addComponent(tf_tema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        l_tema.getAccessibleContext().setAccessibleName("l_tema");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel l_tema;
    private javax.swing.JTextField tf_tema;
    // End of variables declaration//GEN-END:variables

}
