/*
 * PUC-Rio - Pontificia Universidade Catolica
 * Bacharelado em Sistemas de Informacao
 *
 * INF 1405 - Construcao de Sistemas 2010.1     Turma: 3WA
 * Professor: Edmundo Torreao
 *
 * Grupo: Lucas Guarisco
 *        Luiz Felipe Machado
 *        Thyago Lopes
 */

package gui;

import adedanha.Votacao;


/**
 *
 * @author luizfelipe
 */
public class PanelVotacao extends javax.swing.JPanel {

    private String palavra;

    /** Creates new form PanelVotacao */
    public PanelVotacao(String palavra) {
        initComponents();
        
        this.palavra = palavra;
        l_palavra.setText(palavra);
    }

    public String getPalavra() {
        return palavra;
    }
    
    public boolean temSelecionado() {
        if(rb_igual.isSelected() || rb_invalido.isSelected() || rb_valido.isSelected())
            return true;
        return false;
    }

    public String getSelecionadoString() {
        if(rb_igual.isSelected())
            return rb_igual.getText();
        else if(rb_invalido.isSelected())
            return rb_invalido.getText();
        else if(rb_valido.isSelected())
            return rb_valido.getText();
        return null;
    }

    public Votacao getSelecionadoEnum() {
        if(rb_igual.isSelected())
            return Votacao.IGUAL;
        else if(rb_invalido.isSelected())
            return Votacao.INVALIDO;
        else if(rb_valido.isSelected())
            return Votacao.VALIDO;
        return null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gp_votacao = new javax.swing.ButtonGroup();
        l_palavra = new javax.swing.JLabel();
        rb_valido = new javax.swing.JRadioButton();
        rb_invalido = new javax.swing.JRadioButton();
        rb_igual = new javax.swing.JRadioButton();

        l_palavra.setText("jLabel1");

        rb_valido.setText("Valido");

        rb_invalido.setText("Invalido");

        rb_igual.setText("Igual");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_palavra, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_valido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_invalido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_igual))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(l_palavra)
                .addComponent(rb_valido)
                .addComponent(rb_invalido)
                .addComponent(rb_igual))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup gp_votacao;
    private javax.swing.JLabel l_palavra;
    private javax.swing.JRadioButton rb_igual;
    private javax.swing.JRadioButton rb_invalido;
    private javax.swing.JRadioButton rb_valido;
    // End of variables declaration//GEN-END:variables

}
