/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaSugestaoCategoria.java
 *
 * Created on Jun 20, 2010, 7:50:58 PM
 */

package gui;

import adedanha.Tema;
import java.util.TreeSet;
import java.util.Vector;
import javax.swing.JCheckBox;

/**
 *
 * @author luizfelipe
 */
public class TelaSugestaoCategoria extends javax.swing.JFrame {

    private Vector<String> lista_sugestao = new Vector<String>();
    private Vector<JCheckBox> lista_cb = new Vector<JCheckBox>();
    private TelaConfiguracao t;

    /** Creates new form TelaSugestaoCategoria */
    public TelaSugestaoCategoria(TelaConfiguracao c, TreeSet<Tema> temas) {

        this.t = c;
        lista_sugestao.clear();
        lista_cb.clear();
        initComponents();

        lista_cb.add(cb_animal);
        lista_cb.add(cb_carro);
        lista_cb.add(cb_cidade);
        lista_cb.add(cb_cor);
        lista_cb.add(cb_estado);
        lista_cb.add(cb_filme);
        lista_cb.add(cb_fruta);
        lista_cb.add(cb_marca);
        lista_cb.add(cb_nome);
        lista_cb.add(cb_objeto);
        lista_cb.add(cb_pais);
        lista_cb.add(cb_profissao);

        for(Tema t : temas) {
            for(int i = 0; i < lista_cb.size(); ++i) {
                if(t.get_nome().equals(lista_cb.get(i).getText())) {
                    lista_cb.get(i).setSelected(true);
                }
            }
        }

        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fr_sugestaoCategorias = new javax.swing.JPanel();
        cb_nome = new javax.swing.JCheckBox();
        cb_objeto = new javax.swing.JCheckBox();
        cb_fruta = new javax.swing.JCheckBox();
        cb_cor = new javax.swing.JCheckBox();
        cb_animal = new javax.swing.JCheckBox();
        cb_carro = new javax.swing.JCheckBox();
        cb_marca = new javax.swing.JCheckBox();
        cb_profissao = new javax.swing.JCheckBox();
        cb_cidade = new javax.swing.JCheckBox();
        cb_estado = new javax.swing.JCheckBox();
        cb_pais = new javax.swing.JCheckBox();
        cb_filme = new javax.swing.JCheckBox();
        b_adicionar = new javax.swing.JButton();
        b_voltar = new javax.swing.JButton();
        cb_selecionarTodos = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sugestão");
        setAlwaysOnTop(true);
        setName("fr_sugestao"); // NOI18N
        setResizable(false);

        fr_sugestaoCategorias.setBorder(javax.swing.BorderFactory.createTitledBorder("Categorias"));
        fr_sugestaoCategorias.setToolTipText("");

        cb_nome.setText("Nome");

        cb_objeto.setText("Objeto");

        cb_fruta.setText("Fruta");

        cb_cor.setText("Cor");

        cb_animal.setText("Animal");

        cb_carro.setText("Carro");

        cb_marca.setText("Marca");

        cb_profissao.setText("Profissão");

        cb_cidade.setText("Cidade");

        cb_estado.setText("Estado");

        cb_pais.setText("País");

        cb_filme.setText("Filme");

        javax.swing.GroupLayout fr_sugestaoCategoriasLayout = new javax.swing.GroupLayout(fr_sugestaoCategorias);
        fr_sugestaoCategorias.setLayout(fr_sugestaoCategoriasLayout);
        fr_sugestaoCategoriasLayout.setHorizontalGroup(
            fr_sugestaoCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fr_sugestaoCategoriasLayout.createSequentialGroup()
                .addGroup(fr_sugestaoCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_nome)
                    .addComponent(cb_objeto)
                    .addComponent(cb_fruta)
                    .addComponent(cb_cor)
                    .addComponent(cb_animal)
                    .addComponent(cb_carro))
                .addGap(30, 30, 30)
                .addGroup(fr_sugestaoCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_filme)
                    .addComponent(cb_pais)
                    .addComponent(cb_estado)
                    .addComponent(cb_cidade)
                    .addComponent(cb_profissao)
                    .addComponent(cb_marca))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fr_sugestaoCategoriasLayout.setVerticalGroup(
            fr_sugestaoCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fr_sugestaoCategoriasLayout.createSequentialGroup()
                .addGroup(fr_sugestaoCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_nome)
                    .addComponent(cb_marca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fr_sugestaoCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_objeto)
                    .addComponent(cb_profissao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fr_sugestaoCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_fruta)
                    .addComponent(cb_cidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fr_sugestaoCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_cor)
                    .addComponent(cb_estado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fr_sugestaoCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_animal)
                    .addComponent(cb_pais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fr_sugestaoCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_carro)
                    .addComponent(cb_filme))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        b_adicionar.setText("Adicionar");
        b_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_adicionarActionPerformed(evt);
            }
        });

        b_voltar.setText("Voltar");
        b_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_voltarActionPerformed(evt);
            }
        });

        cb_selecionarTodos.setText("Selecionar todos");
        cb_selecionarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_selecionarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_adicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(b_voltar)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fr_sugestaoCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cb_selecionarTodos)
                        .addContainerGap(86, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fr_sugestaoCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_selecionarTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_adicionar)
                    .addComponent(b_voltar)))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-205)/2, (screenSize.height-289)/2, 205, 289);
    }// </editor-fold>//GEN-END:initComponents

    private void b_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_voltarActionPerformed
        lista_sugestao.clear();
        this.setVisible(false);
    }//GEN-LAST:event_b_voltarActionPerformed

    private void b_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_adicionarActionPerformed
        for(int i = 0; i < lista_cb.size(); ++i) {
            if(lista_cb.get(i).isSelected())
                lista_sugestao.add(lista_cb.get(i).getText());
        }

        this.t.setListaCategorias(lista_sugestao);
        this.setVisible(false);
    }//GEN-LAST:event_b_adicionarActionPerformed

    private void cb_selecionarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_selecionarTodosActionPerformed
        boolean seleciona;
        if(cb_selecionarTodos.isSelected())
            seleciona = true;
        else
            seleciona = false;
        
        for(JCheckBox cb : lista_cb) {
            cb.setSelected(seleciona);
        }
    }//GEN-LAST:event_cb_selecionarTodosActionPerformed

    public Vector<String> getListaSugestao() {
        return lista_sugestao;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_adicionar;
    private javax.swing.JButton b_voltar;
    private javax.swing.JCheckBox cb_animal;
    private javax.swing.JCheckBox cb_carro;
    private javax.swing.JCheckBox cb_cidade;
    private javax.swing.JCheckBox cb_cor;
    private javax.swing.JCheckBox cb_estado;
    private javax.swing.JCheckBox cb_filme;
    private javax.swing.JCheckBox cb_fruta;
    private javax.swing.JCheckBox cb_marca;
    private javax.swing.JCheckBox cb_nome;
    private javax.swing.JCheckBox cb_objeto;
    private javax.swing.JCheckBox cb_pais;
    private javax.swing.JCheckBox cb_profissao;
    private javax.swing.JCheckBox cb_selecionarTodos;
    private javax.swing.JPanel fr_sugestaoCategorias;
    // End of variables declaration//GEN-END:variables

}
