/*
 * PUC-Rio - Pontificia Universidade Catolica
 * Bacharelado em Sistemas de Informacao
 *
 * INF 1405 - Construcao de Sistemas 2010.1     Turma: 3WA
 * Professor: Edmundo Torreao
 *
 * Grupo: Lucas Guarisco
 *        Luiz Felipe Machado
 *        Thyago Lopes
 */
package gui;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import tratamento_erro.ErroComunicacao;

import adedanha.Usuario;
import controller.Controller;

/**
 *
 * @author luizfelipe
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Controlador do jogo.
     */
    private Controller controller;

    /** Creates new form TelaInicial */
    public TelaInicial() {
        controller = new Controller();

        initComponents();

        tf_ip.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        criarEntrarJogoGrupo = new javax.swing.ButtonGroup();
        l_apelido = new javax.swing.JLabel();
        tf_apelido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf_porta = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rb_criarJogo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        tf_ip = new javax.swing.JFormattedTextField();
        rb_entrarJogo = new javax.swing.JRadioButton();
        b_conectar = new javax.swing.JButton();
        b_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adedanha");
        setName(""); // NOI18N
        setResizable(false);

        l_apelido.setText("Apelido: ");

        tf_apelido.setText("Apelido");

        jLabel1.setText("Porta:");

        tf_porta.setText("9091");
        tf_porta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_portaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        criarEntrarJogoGrupo.add(rb_criarJogo);
        rb_criarJogo.setSelected(true);
        rb_criarJogo.setText("Criar um jogo");
        rb_criarJogo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rb_criarJogoStateChanged(evt);
            }
        });

        jLabel2.setText("IP do servidor:");

        tf_ip.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_ip.setText("127.0.0.001");
        tf_ip.setToolTipText("Endereco IP do servidor no formato XXX.XXX.XXX.XXX");
        tf_ip.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        tf_ip.setPreferredSize(new java.awt.Dimension(70, 25));

        criarEntrarJogoGrupo.add(rb_entrarJogo);
        rb_entrarJogo.setText("Entrar em um jogo");
        rb_entrarJogo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rb_entrarJogoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_criarJogo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tf_ip, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                    .addComponent(rb_entrarJogo))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rb_criarJogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_entrarJogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        b_conectar.setText("Conectar");
        b_conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	SwingUtilities.invokeLater(runConecta);
            }
        });

        b_sair.setText("Sair");
        b_sair.setMaximumSize(new java.awt.Dimension(77, 23));
        b_sair.setMinimumSize(new java.awt.Dimension(77, 23));
        b_sair.setPreferredSize(new java.awt.Dimension(77, 23));
        b_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(l_apelido))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_porta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_apelido, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(b_conectar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(b_sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_apelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_apelido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_porta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_conectar)
                    .addComponent(b_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        b_conectar.getAccessibleContext().setAccessibleName(null);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-265)/2, (screenSize.height-225)/2, 265, 225);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_portaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_portaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_portaActionPerformed
    Runnable runConecta = new Runnable() {

        public void run() {
            if (tf_apelido.getText().isEmpty() || tf_porta.getText().isEmpty()) {
                //TODO (Thyago, 2010-06-13) Notificar erro ao usuario.
                return;
            }

            Integer porta;
            porta = new Integer(tf_porta.getText());
            
            Usuario usuario = null;
            // Criar um novo jogo sendo o servidor
            if (rb_criarJogo.isSelected()) {
                controller.inicializaServidor(9010);
                usuario = new Usuario(tf_apelido.getText(), true);
            } else {
                usuario = new Usuario(tf_apelido.getText());
            }

            try {
                controller.conectaCliente(TelaInicial.this, tf_ip.getText(), porta);
                boolean added = controller.add_usuario(usuario);
                if (added) {
                    controller.registraCliente();
                    TelaInicial.this.setVisible(false);
                    TelaConfiguracao tela = new TelaConfiguracao(controller);
                    tela.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(TelaInicial.this, "Usuario ja existe", "Erro na criacao do usuario", JOptionPane.ERROR_MESSAGE);
                }
            } catch (ErroComunicacao e) {
                JOptionPane.showMessageDialog(TelaInicial.this, e.getMessage(), "Erro na criacao do usuario", JOptionPane.ERROR_MESSAGE);
            }
        }
    };

    private void b_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_b_sairActionPerformed

    private void rb_entrarJogoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rb_entrarJogoStateChanged
        if (rb_entrarJogo.isSelected()) {
            tf_ip.setEnabled(true);
        }
    }//GEN-LAST:event_rb_entrarJogoStateChanged

    private void rb_criarJogoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rb_criarJogoStateChanged
        if (rb_criarJogo.isSelected()) {
            tf_ip.setEnabled(false);
        }
    }//GEN-LAST:event_rb_criarJogoStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_conectar;
    private javax.swing.JButton b_sair;
    private javax.swing.ButtonGroup criarEntrarJogoGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l_apelido;
    private javax.swing.JRadioButton rb_criarJogo;
    private javax.swing.JRadioButton rb_entrarJogo;
    private javax.swing.JTextField tf_apelido;
    private javax.swing.JFormattedTextField tf_ip;
    private javax.swing.JTextField tf_porta;
    // End of variables declaration//GEN-END:variables
}
